[toolchain]
package_manager = "yarn"
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
game_escrow = "ASLA3yCccjSoMAxoYBciM5vqdCZKcedd2QkbVWtjQEL4"

[programs.devnet]
game_escrow = "ASLA3yCccjSoMAxoYBciM5vqdCZKcedd2QkbVWtjQEL4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

